version: '3.8'

services:
  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    container_name: docchat-server

  client:
    build:
      context: ./client
      args:
        - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
        - VITE_API_URL=${VITE_API_URL}
    ports:
      - "80:80"
    depends_on:
      - server
    container_name: docchat-client
